package com.kraeutertee.util

// ──────────────────────────────────────────────────────────────────────────────
// Static data model for built-in herbs
// ──────────────────────────────────────────────────────────────────────────────
data class HerbInfo(
    val id: String,
    val name: String,
    val latinName: String,
    val emoji: String,
    val shortDescription: String,
    val harvestPart: String,        // "Blätter", "Blüten", "Wurzel", "Samen", "Früchte"
    val harvestMonths: List<Int>,   // 1–12
    val harvestTips: String,
    val dryingDays: Int,
    val dryingTempMax: Int,         // °C
    val dryingMethod: String,
    val storageMonths: Int,
    val teaInfo: String,            // brewing tips
    val brewingTempC: Int,
    val brewingMinutes: Int,
    val effects: List<String>,
    val compatibleWith: List<String>,  // herb IDs
    val gardenTips: String,
    val warningsDE: String,
    val category: String            // "Beruhigung", "Erkältung", "Verdauung", etc.
)

object HerbDatabase {

    val all: List<HerbInfo> = listOf(

        HerbInfo(
            id = "kamille",
            name = "Echte Kamille",
            latinName = "Matricaria chamomilla",
            emoji = "🌼",
            shortDescription = "Die Kamille ist das Universalheilmittel der Naturheilkunde – beruhigend, entzündungshemmend und magenfreundlich.",
            harvestPart = "Blüten",
            harvestMonths = listOf(5, 6, 7, 8),
            harvestTips = "Blüten ernten wenn sie vollständig geöffnet sind und die Blütenblätter leicht nach unten zeigen. Am besten an trockenen Vormittagen nach dem Tau. Die Blüten täglich kontrollieren – sie reifen schnell nach.",
            dryingDays = 7,
            dryingTempMax = 40,
            dryingMethod = "Ausgebreitet auf Tüchern oder Papier, im Schatten, gut belüftet. Nicht in direkter Sonne trocknen!",
            storageMonths = 12,
            teaInfo = "1–2 TL getrocknete Blüten pro Tasse, 5–10 Min. ziehen lassen, abgedeckt. Heiß: 80–90°C.",
            brewingTempC = 85,
            brewingMinutes = 8,
            effects = listOf("Beruhigend", "Entzündungshemmend", "Magenberuhigend", "Krampflösend", "Schlaffördernd"),
            compatibleWith = listOf("melisse", "baldrian", "lavendel", "pfefferminze"),
            gardenTips = "Selbstaussäer, liebt sonnige sandige Böden. Einfach zu kultivieren.",
            warningsDE = "Bei Allergie gegen Korbblütler Vorsicht. In der Schwangerschaft nur mäßig konsumieren.",
            category = "Beruhigung"
        ),

        HerbInfo(
            id = "pfefferminze",
            name = "Pfefferminze",
            latinName = "Mentha × piperita",
            emoji = "🌿",
            shortDescription = "Pfefferminze – kühlend, belebend und unverzichtbar für die heimische Teeküche.",
            harvestPart = "Blätter",
            harvestMonths = listOf(5, 6, 7, 8, 9),
            harvestTips = "Blätter vor der Blüte ernten, da dann der Mentholgehalt am höchsten ist. Triebspitzen abschneiden, das fördert buschiges Wachstum. Immer morgens nach dem Tau ernten.",
            dryingDays = 5,
            dryingTempMax = 40,
            dryingMethod = "In kleinen Bündeln kopfüber aufhängen oder auf Gittern ausbreiten. Schatten, gute Luftzirkulation.",
            storageMonths = 18,
            teaInfo = "1 EL frische oder 1 TL getrocknete Blätter, 5–7 Min. ziehen, abdecken um ätherische Öle zu halten. Nicht kochen!",
            brewingTempC = 90,
            brewingMinutes = 6,
            effects = listOf("Kühlend", "Verdauungsfördernd", "Kopfschmerzlindernd", "Belebend", "Antibakteriell"),
            compatibleWith = listOf("kamille", "zitronengras", "fenchel", "ingwer"),
            gardenTips = "Sehr wüchsig, am besten im Topf oder mit Rhizomsperre pflanzen. Braucht feuchten Boden und Halbschatten.",
            warningsDE = "Nicht für Babys und Kleinkinder geeignet (Menthol). Bei Sodbrennen vorsichtig dosieren.",
            category = "Verdauung"
        ),

        HerbInfo(
            id = "melisse",
            name = "Zitronenmelisse",
            latinName = "Melissa officinalis",
            emoji = "🍃",
            shortDescription = "Sanft beruhigend mit wunderbarem Zitronenduft – die Melisse ist ein Segen bei Stress und Unruhe.",
            harvestPart = "Blätter",
            harvestMonths = listOf(5, 6, 7, 8, 9),
            harvestTips = "Blätter vor der Blüte ernten, da dann der Duft am intensivsten ist. Triebspitzen abschneiden. Nach der Blüte zweite Ernte möglich.",
            dryingDays = 5,
            dryingTempMax = 35,
            dryingMethod = "Bei sehr niedriger Temperatur trocknen, da die ätherischen Öle flüchtig sind. Frisch verwenden ist optimal.",
            storageMonths = 12,
            teaInfo = "2 TL frische oder 1 TL getrocknete Blätter, 5–8 Min. abgedeckt ziehen. Wasser nur 70–80°C.",
            brewingTempC = 75,
            brewingMinutes = 7,
            effects = listOf("Beruhigend", "Antiviral (Herpes)", "Schlaffördernd", "Stimmungsaufhellend", "Nervenstärkend"),
            compatibleWith = listOf("kamille", "baldrian", "lavendel", "johanniskraut"),
            gardenTips = "Liebt Halbschatten, anspruchslos. Wächst üppig und duftet herrlich. Guter Bienenmagnet.",
            warningsDE = "Kann Schilddrüsenfunktion beeinflussen – bei Schilddrüsenerkrankungen Arzt befragen.",
            category = "Beruhigung"
        ),

        HerbInfo(
            id = "baldrian",
            name = "Baldrian",
            latinName = "Valeriana officinalis",
            emoji = "💜",
            shortDescription = "Baldrian ist das bekannteste pflanzliche Schlafmittel – entspannend und beruhigend.",
            harvestPart = "Wurzel",
            harvestMonths = listOf(9, 10, 11),
            harvestTips = "Wurzeln im Herbst des zweiten Jahres ausgraben. Pflanzen sollten mindestens 2 Jahre alt sein. Wurzeln waschen und in Scheiben schneiden.",
            dryingDays = 14,
            dryingTempMax = 40,
            dryingMethod = "In Scheiben schneiden und bei 35–40°C im Dörrgerät oder luftig aufgehängt trocknen. Charakteristischer Geruch entsteht beim Trocknen.",
            storageMonths = 24,
            teaInfo = "1 TL getrocknete Wurzel, 10–15 Min. ziehen lassen. Abends trinken, schmeckt erdnussig-kräftig.",
            brewingTempC = 80,
            brewingMinutes = 12,
            effects = listOf("Schlaffördernd", "Beruhigend", "Angstlösend", "Muskelentspannend"),
            compatibleWith = listOf("melisse", "hopfen", "kamille", "lavendel"),
            gardenTips = "Braucht feuchten Boden, wächst in der Natur an Bachufern. Mehrjährig, wird bis 150 cm hoch.",
            warningsDE = "Nicht mit Schlafmitteln kombinieren. Tagesmüdigkeit möglich. Nicht Auto fahren!",
            category = "Schlaf"
        ),

        HerbInfo(
            id = "lavendel",
            name = "Lavendel",
            latinName = "Lavandula angustifolia",
            emoji = "💐",
            shortDescription = "Lavendel beruhigt Nerven und Geist, fördert den Schlaf und duftet unvergleichlich.",
            harvestPart = "Blüten",
            harvestMonths = listOf(6, 7, 8),
            harvestTips = "Blütenstängel ernten wenn etwa die Hälfte der Blüten geöffnet ist. Kurze Stängel lassen, damit die Pflanze wieder austreibt.",
            dryingDays = 10,
            dryingTempMax = 35,
            dryingMethod = "In Bündeln kopfüber im Schatten aufhängen. Der Duft bleibt lange erhalten.",
            storageMonths = 18,
            teaInfo = "1 TL Blüten, 5–7 Min. bei 90°C ziehen. Sparsam verwenden – intensiver Geschmack!",
            brewingTempC = 90,
            brewingMinutes = 6,
            effects = listOf("Beruhigend", "Schlaffördernd", "Kopfschmerzlindernd", "Angstlösend", "Antiseptisch"),
            compatibleWith = listOf("kamille", "melisse", "baldrian", "rose"),
            gardenTips = "Liebt sonnige trockene Standorte, kalkhaltiger Boden. Winterhart. Gut für Bienen.",
            warningsDE = "Sparsam dosieren. In der Schwangerschaft mäßig verwenden.",
            category = "Beruhigung"
        ),

        HerbInfo(
            id = "johanniskraut",
            name = "Johanniskraut",
            latinName = "Hypericum perforatum",
            emoji = "☀️",
            shortDescription = "Das Sonnenkraut – bekannt für seine stimmungsaufhellende Wirkung bei leichten Depressionen.",
            harvestPart = "Blüten",
            harvestMonths = listOf(6, 7, 8),
            harvestTips = "Blüten und Knospen um den Johannistag (24. Juni) ernten. Test: Blüte zwischen Fingern drücken – roter Saft = richtige Zeit.",
            dryingDays = 7,
            dryingTempMax = 40,
            dryingMethod = "Im Schatten trocknen, nicht in der Sonne – Wirkstoffe sind lichtempfindlich!",
            storageMonths = 12,
            teaInfo = "2 TL getrocknete Blüten, 10 Min. ziehen lassen. Regelmäßig trinken für Wirkung (mind. 6 Wochen).",
            brewingTempC = 90,
            brewingMinutes = 10,
            effects = listOf("Stimmungsaufhellend", "Antidepressiv", "Nervenstärkend", "Wundheilend"),
            compatibleWith = listOf("melisse", "lavendel", "baldrian"),
            gardenTips = "Wächst wild auf trockenen, sonnigen Wiesen. Im Garten: magerer, durchlässiger Boden.",
            warningsDE = "WICHTIG: Wechselwirkungen mit vielen Medikamenten (Antibabypille, Antidepressiva, HIV-Medikamente)! Arzt fragen. Kann Lichtempfindlichkeit erhöhen.",
            category = "Stimmung"
        ),

        HerbInfo(
            id = "hagebutte",
            name = "Hagebutte",
            latinName = "Rosa canina",
            emoji = "🔴",
            shortDescription = "Hagebutten sind wahre Vitamin-C-Bomben – ideal für Erkältungszeit und zur Immunstärkung.",
            harvestPart = "Früchte",
            harvestMonths = listOf(9, 10, 11),
            harvestTips = "Nach dem ersten Frost ernten – dann sind sie süßer und weicher. Tiefrot, etwas weich drücken beim Test.",
            dryingDays = 21,
            dryingTempMax = 50,
            dryingMethod = "Halbieren, Kerne und Härchen entfernen (reizen Hals!), dann bei 40–50°C im Dörrgerät. Oder ganz trocknen und später aufbrechen.",
            storageMonths = 24,
            teaInfo = "1–2 EL getrocknete Früchte, 15 Min. köcheln lassen (nicht kochen). Honig dazugeben.",
            brewingTempC = 95,
            brewingMinutes = 15,
            effects = listOf("Immunstärkend", "Vitamin-C-reich", "Entzündungshemmend", "Gelenkunterstützend"),
            compatibleWith = listOf("holunderblüte", "thymian", "ingwer"),
            gardenTips = "Robuster Strauch, wächst überall. Hecke als Wildtierschutz. Keine besonderen Ansprüche.",
            warningsDE = "Kerne und Kernhärchen entfernen – können Schleimhäute reizen.",
            category = "Immunsystem"
        ),

        HerbInfo(
            id = "holunderblüte",
            name = "Holunderblüte",
            latinName = "Sambucus nigra",
            emoji = "🤍",
            shortDescription = "Holunderblüten sind aromatisch und helfen bei Erkältungen, Fieber und als Frühlingstonikum.",
            harvestPart = "Blüten",
            harvestMonths = listOf(5, 6),
            harvestTips = "Dolden ernten wenn voll geöffnet und aromatisch duftend – oft morgens. Keine verblühten oder unreifen Dolden!",
            dryingDays = 5,
            dryingTempMax = 35,
            dryingMethod = "Dolden auf Papier ausbreiten, Blüten nach dem Trocknen abstreifen. Schnell trocknen.",
            storageMonths = 12,
            teaInfo = "1 EL Blüten, 5–8 Min. bei 90°C ziehen. Mit Honig und Zitrone – klassisch bei Erkältung.",
            brewingTempC = 90,
            brewingMinutes = 7,
            effects = listOf("Schweißtreibend", "Fiebersenkend", "Schleimlösend", "Immunstärkend"),
            compatibleWith = listOf("hagebutte", "thymian", "ingwer", "kamille"),
            gardenTips = "Schnell wachsender Strauch/Baum, liebt feuchte Standorte. Vögel lieben die Beeren.",
            warningsDE = "Nur Blüten des Schwarzen Holunders verwenden (nicht Zwergholunder!). Grüne Teile und rohe Beeren leicht giftig.",
            category = "Erkältung"
        ),

        HerbInfo(
            id = "brennnessel",
            name = "Brennnessel",
            latinName = "Urtica dioica",
            emoji = "🌱",
            shortDescription = "Die Brennnessel ist ein Kraftpaket voller Mineralien, Vitamine und entwässernder Wirkstoffe.",
            harvestPart = "Blätter",
            harvestMonths = listOf(3, 4, 5, 6, 9, 10),
            harvestTips = "Junge Triebspitzen ernten (obere 4–6 Blattpaare). Handschuhe tragen! Im Frühjahr und nach dem Rückschnitt im Herbst.",
            dryingDays = 5,
            dryingTempMax = 40,
            dryingMethod = "Auf Gittern ausbreiten oder in Bündeln hängen. Beim Trocknen verliert sie ihre Brennhaare.",
            storageMonths = 12,
            teaInfo = "2 TL getrocknete Blätter, 10 Min. ziehen lassen. Viel trinken (entwässernd).",
            brewingTempC = 95,
            brewingMinutes = 10,
            effects = listOf("Entwässernd", "Mineralstoffreich", "Eisenreich", "Entschlackend", "Blutdrucksenkend"),
            compatibleWith = listOf("loewenzahn", "pfefferminze", "ringelblume"),
            gardenTips = "Wächst überall, liebt stickstoffreichen Boden. Schmetterlingsnahrung (Kleiner Fuchs etc.).",
            warningsDE = "Bei Nieren- oder Herzerkrankungen mit Wassereinlagerungen – Arzt befragen.",
            category = "Entgiftung"
        ),

        HerbInfo(
            id = "schafgarbe",
            name = "Schafgarbe",
            latinName = "Achillea millefolium",
            emoji = "⚪",
            shortDescription = "Schafgarbe ist ein Allrounder – blutungsemmend, entzündungshemmend und magenfreundlich.",
            harvestPart = "Blüten",
            harvestMonths = listOf(6, 7, 8, 9),
            harvestTips = "Blüten und obere Blätter ernten wenn voll geöffnet. An trockenen Tagen ernten.",
            dryingDays = 7,
            dryingTempMax = 40,
            dryingMethod = "In Bündeln aufhängen oder ausgebreitet trocknen. Luftige, schattige Orte.",
            storageMonths = 12,
            teaInfo = "1–2 TL, 10 Min. ziehen lassen. Leicht bitter – Honig hilft.",
            brewingTempC = 90,
            brewingMinutes = 10,
            effects = listOf("Blutstillend", "Entzündungshemmend", "Magenberuhigend", "Krampflösend", "Fiebersenkend"),
            compatibleWith = listOf("kamille", "pfefferminze", "melisse", "ringelblume"),
            gardenTips = "Sehr anspruchslos, wächst auf mageren Wiesen. Guter Begleitpflanzen.",
            warningsDE = "Allergie gegen Korbblütler möglich. In der Schwangerschaft meiden.",
            category = "Verdauung"
        ),

        HerbInfo(
            id = "loewenzahn",
            name = "Löwenzahn",
            latinName = "Taraxacum officinale",
            emoji = "🌻",
            shortDescription = "Löwenzahn reinigt Leber und Nieren, regt den Stoffwechsel an – das Frühlings-Detoxkraut.",
            harvestPart = "Blätter",
            harvestMonths = listOf(3, 4, 5, 9, 10),
            harvestTips = "Junge Blätter vor der Blüte ernten (weniger bitter). Im Herbst erneut möglich. Wurzeln im Herbst für Tee.",
            dryingDays = 7,
            dryingTempMax = 40,
            dryingMethod = "Blätter auf Gittern ausbreiten. Wurzeln in Scheiben bei 40°C im Dörrgerät.",
            storageMonths = 12,
            teaInfo = "1–2 TL Blätter oder Wurzel, 10 Min. ziehen. Leicht bitter-aromatisch.",
            brewingTempC = 95,
            brewingMinutes = 10,
            effects = listOf("Leberreinigend", "Entwässernd", "Verdauungsfördernd", "Mineralstoffreich"),
            compatibleWith = listOf("brennnessel", "pfefferminze"),
            gardenTips = "Überall vorhanden. Im Garten tolerieren – wertvolle Wildpflanze.",
            warningsDE = "Bei Gallensteinen oder Gallenproblemen Arzt befragen.",
            category = "Entgiftung"
        ),

        HerbInfo(
            id = "thymian",
            name = "Thymian",
            latinName = "Thymus vulgaris",
            emoji = "🌿",
            shortDescription = "Thymian ist das Erkältungskraut schlechthin – schleimlösend, antiseptisch und wärmend.",
            harvestPart = "Blätter",
            harvestMonths = listOf(4, 5, 6, 7, 8, 9),
            harvestTips = "Triebspitzen vor der vollen Blüte ernten. Nicht mehr als 1/3 der Pflanze auf einmal.",
            dryingDays = 7,
            dryingTempMax = 40,
            dryingMethod = "In kleinen Bündeln trocknen oder auf Gittern. Stängel und Blätter verwenden.",
            storageMonths = 18,
            teaInfo = "1 TL frisch oder getrocknet, 10 Min. abgedeckt ziehen. Mit Honig und Zitrone.",
            brewingTempC = 90,
            brewingMinutes = 10,
            effects = listOf("Schleimlösend", "Antiseptisch", "Antibakteriell", "Huststillend", "Immunstärkend"),
            compatibleWith = listOf("holunderblüte", "ingwer", "salbei", "hagebutte"),
            gardenTips = "Liebt Sonne und durchlässigen Boden. Sehr pflegeleicht. Winterhart.",
            warningsDE = "In großen Mengen in der Schwangerschaft meiden.",
            category = "Erkältung"
        ),

        HerbInfo(
            id = "salbei",
            name = "Echter Salbei",
            latinName = "Salvia officinalis",
            emoji = "🟢",
            shortDescription = "Salbei – antibakteriell, schweißhemmend und bei Halsschmerzen unersetzlich.",
            harvestPart = "Blätter",
            harvestMonths = listOf(4, 5, 6, 7, 8, 9),
            harvestTips = "Junge Blätter vor der Blüte ernten. Triebspitzen abschneiden für buschiges Wachstum.",
            dryingDays = 7,
            dryingTempMax = 40,
            dryingMethod = "In Bündeln oder auf Gittern, im Schatten, luftig. Intensiver Duft beim Trocknen.",
            storageMonths = 18,
            teaInfo = "3–4 Blätter frisch oder 1 TL getrocknet, 5–8 Min. ziehen. Mit Zitrone bei Halsschmerzen.",
            brewingTempC = 90,
            brewingMinutes = 7,
            effects = listOf("Antibakteriell", "Schweißhemmend", "Entzündungshemmend", "Gedächtnisfördernd"),
            compatibleWith = listOf("thymian", "rosmarin", "pfefferminze"),
            gardenTips = "Sonniger trockener Standort. Mehrjährig, verholzt mit der Zeit – regelmäßig schneiden.",
            warningsDE = "In der Schwangerschaft und Stillzeit nicht in großen Mengen. Thujonggehalt beachten – nicht täglich über lange Zeit in hoher Dosis.",
            category = "Erkältung"
        ),

        HerbInfo(
            id = "rosmarin",
            name = "Rosmarin",
            latinName = "Salvia rosmarinus",
            emoji = "🌲",
            shortDescription = "Rosmarin belebt und aktiviert den Kreislauf – ideal für müde Geister und schwache Durchblutung.",
            harvestPart = "Blätter",
            harvestMonths = listOf(3, 4, 5, 6, 7, 8, 9, 10),
            harvestTips = "Ganzjährig erntbar. Weiche Triebspitzen bevorzugen. Nicht mehr als 1/3 ernten.",
            dryingDays = 7,
            dryingTempMax = 40,
            dryingMethod = "Bündel oder einzelne Zweige trocknen. Nadeln bleiben gut erhalten.",
            storageMonths = 24,
            teaInfo = "1 TL Nadeln, 8–10 Min. ziehen. Morgens trinken – belebend. Nicht abends!",
            brewingTempC = 95,
            brewingMinutes = 9,
            effects = listOf("Kreislaufanregend", "Durchblutungsfördernd", "Gedächtnisfördernd", "Konzentration"),
            compatibleWith = listOf("salbei", "thymian", "zitronenmelisse"),
            gardenTips = "Braucht Winterschutz in rauen Lagen. Sonnig, kalkhaltig, trocken.",
            warningsDE = "Bei Bluthochdruck und Epilepsie meiden. In Schwangerschaft nicht in großen Mengen.",
            category = "Kreislauf"
        ),

        HerbInfo(
            id = "fenchel",
            name = "Fenchel",
            latinName = "Foeniculum vulgare",
            emoji = "🌾",
            shortDescription = "Fenchel – das klassische Blähungsmittel, sanft und wohlschmeckend für Jung und Alt.",
            harvestPart = "Samen",
            harvestMonths = listOf(8, 9, 10),
            harvestTips = "Dolden ernten wenn Samen gelblich-braun sind. Dolden in Papiertüten hängen – Samen fallen ab.",
            dryingDays = 14,
            dryingTempMax = 35,
            dryingMethod = "Samen auf Papier nachreifen lassen, dann trocken in dunkle Gläser füllen.",
            storageMonths = 24,
            teaInfo = "1 TL leicht angestoßene Samen, 10 Min. ziehen. Für Babys geeignet (verdünnt).",
            brewingTempC = 95,
            brewingMinutes = 10,
            effects = listOf("Blähungslindernd", "Krampflösend", "Verdauungsfördernd", "Schleimlösend"),
            compatibleWith = listOf("kamille", "kümmel", "pfefferminze", "anis"),
            gardenTips = "Zwei- bis mehrjährig, bis 200 cm hoch. Sonnig, trocken. Nicht neben Koriander pflanzen.",
            warningsDE = "Bei Ödemen durch Herz- oder Nierenprobleme Arzt befragen.",
            category = "Verdauung"
        ),

        HerbInfo(
            id = "ingwer",
            name = "Ingwer",
            latinName = "Zingiber officinale",
            emoji = "🫚",
            shortDescription = "Ingwer wärmt, regt die Verdauung an, stärkt das Immunsystem und lindert Übelkeit.",
            harvestPart = "Wurzel",
            harvestMonths = listOf(10, 11),
            harvestTips = "Im Topf kultivieren (nicht winterhart). Im Herbst Knolle ausgraben. Frisch verwenden oder trocknen.",
            dryingDays = 14,
            dryingTempMax = 40,
            dryingMethod = "In dünne Scheiben schneiden, bei 40°C im Dörrgerät trocknen.",
            storageMonths = 24,
            teaInfo = "3–5 Scheiben frisch oder 1 TL gemahlen, 10 Min. ziehen. Mit Honig und Zitrone.",
            brewingTempC = 95,
            brewingMinutes = 10,
            effects = listOf("Wärmend", "Übelkeitslindernd", "Immunstärkend", "Entzündungshemmend", "Durchblutungsfördernd"),
            compatibleWith = listOf("holunderblüte", "zitrone", "hagebutte", "kurkuma"),
            gardenTips = "Als Kübelpflanze (mind. 10 L Topf). Halbschatten, warm, feucht. Im Haus überwintern.",
            warningsDE = "Bei Gallensteinen und Blutgerinnungshemmern Arzt befragen. In der Schwangerschaft moderate Mengen.",
            category = "Immunsystem"
        ),

        HerbInfo(
            id = "lindenblüte",
            name = "Lindenblüte",
            latinName = "Tilia cordata / platyphyllos",
            emoji = "🌳",
            shortDescription = "Lindenblüten sind sanft beruhigend, schweißtreibend bei Erkältung und wunderbar aromatisch.",
            harvestPart = "Blüten",
            harvestMonths = listOf(6, 7),
            harvestTips = "Blüten ernten wenn voll geöffnet und duftend (wenige Tage Fenster!). Samen noch grün.",
            dryingDays = 5,
            dryingTempMax = 35,
            dryingMethod = "Auf Papier ausbreiten, Blüten mit Tragblättern trocknen. Schnell trocknen.",
            storageMonths = 12,
            teaInfo = "1–2 TL getrocknete Blüten, 10 Min. ziehen lassen. Sanft und mild.",
            brewingTempC = 90,
            brewingMinutes = 10,
            effects = listOf("Beruhigend", "Schweißtreibend", "Erkältungslindernd", "Schlaffördend"),
            compatibleWith = listOf("kamille", "holunderblüte", "ingwer", "melisse"),
            gardenTips = "Großer Baum, braucht viel Platz. Wächst in Parks und an Straßen – dort ernten.",
            warningsDE = "Zu alte Blüten (braun) können Herzbeschwerden verursachen. Nur frische Blüten verwenden.",
            category = "Erkältung"
        ),

        HerbInfo(
            id = "ringelblume",
            name = "Ringelblume",
            latinName = "Calendula officinalis",
            emoji = "🧡",
            shortDescription = "Ringelblumen haben entzündungshemmende Wirkung und sind schön anzusehen – innen und außen heilsam.",
            harvestPart = "Blüten",
            harvestMonths = listOf(6, 7, 8, 9, 10),
            harvestTips = "Blüten täglich ernten wenn voll geöffnet. Je mehr du erntets, desto mehr blüht die Pflanze.",
            dryingDays = 7,
            dryingTempMax = 40,
            dryingMethod = "Auf Gittern ausbreiten, täglich wenden. Vollständig trocknen damit kein Schimmel entsteht.",
            storageMonths = 12,
            teaInfo = "1–2 TL Blüten, 10 Min. ziehen lassen. Goldene Farbe, leicht herb-aromatisch.",
            brewingTempC = 90,
            brewingMinutes = 10,
            effects = listOf("Entzündungshemmend", "Wundheilend", "Krampflösend", "Magenberuhigend"),
            compatibleWith = listOf("kamille", "schafgarbe", "brennnessel"),
            gardenTips = "Einfach aus Samen, selbstaussäend. Liebt sonnige Plätze. Langer Flor bis Frost.",
            warningsDE = "Allergie gegen Korbblütler möglich.",
            category = "Verdauung"
        ),

        HerbInfo(
            id = "echinacea",
            name = "Echinacea",
            latinName = "Echinacea purpurea",
            emoji = "🌸",
            shortDescription = "Der Sonnenhut ist der König der Immunstärker – aktiviert die körpereigenen Abwehrkräfte.",
            harvestPart = "Blüten",
            harvestMonths = listOf(7, 8, 9),
            harvestTips = "Blüten und Blätter ernten, Wurzeln erst ab dem 3. Jahr im Herbst. Wurzeln sind am wirksamsten.",
            dryingDays = 10,
            dryingTempMax = 40,
            dryingMethod = "Blüten auf Gittern trocknen. Wurzeln in Scheiben zerteilen.",
            storageMonths = 18,
            teaInfo = "1 TL Blüten oder Wurzel, 10–15 Min. ziehen. Nicht länger als 8 Wochen täglich.",
            brewingTempC = 95,
            brewingMinutes = 12,
            effects = listOf("Immunstärkend", "Antibakteriell", "Antiviral", "Entzündungshemmend"),
            compatibleWith = listOf("hagebutte", "holunderblüte", "ingwer", "thymian"),
            gardenTips = "Mehrjährig, schöne Zierpflanze. Liebt sonnige Standorte, robust und ausdauernd.",
            warningsDE = "Bei Autoimmunerkrankungen (MS, Lupus etc.) nicht verwenden. Nicht länger als 8 Wochen am Stück.",
            category = "Immunsystem"
        ),

        HerbInfo(
            id = "verbena",
            name = "Eisenkraut",
            latinName = "Verbena officinalis",
            emoji = "🟣",
            shortDescription = "Eisenkraut stärkt die Nerven, lindert Migräne und hat eine leicht entspannende Wirkung.",
            harvestPart = "Blüten",
            harvestMonths = listOf(7, 8, 9),
            harvestTips = "Blütenrispen ernten wenn erste Blüten geöffnet sind. Triebspitzen abschneiden.",
            dryingDays = 7,
            dryingTempMax = 35,
            dryingMethod = "Bündel oder Gitter trocknen, schattig und luftig.",
            storageMonths = 12,
            teaInfo = "1–2 TL, 8–10 Min. ziehen lassen. Leicht bitter, mit Honig süßen.",
            brewingTempC = 90,
            brewingMinutes = 9,
            effects = listOf("Nervenstärkend", "Kopfschmerzlindernd", "Leberunterstützend", "Entspannend"),
            compatibleWith = listOf("melisse", "lavendel", "baldrian"),
            gardenTips = "Wächst gerne an sonnigen, warmen Plätzen. Anspruchslos.",
            warningsDE = "In der Schwangerschaft meiden (wehenanregend).",
            category = "Beruhigung"
        )
    )

    fun getById(id: String): HerbInfo? = all.find { it.id == id }

    fun getByCategory(category: String): List<HerbInfo> = all.filter { it.category == category }

    val categories: List<String> get() =
        (all.map { it.category } + listOf("Sonstige")).distinct().sorted()

    /** Harvest months adjusted by latitude offset (positive = later, negative = earlier) */
    fun adjustedHarvestMonths(herb: HerbInfo, latitudeOffset: Int): List<Int> {
        return herb.harvestMonths.map { m ->
            ((m - 1 + latitudeOffset + 12) % 12) + 1
        }.distinct().sorted()
    }
}
